### ISSUE TITLE
BeamOperator: batchUpdates does not respect end timestamp

### ISSUE THREAD

**Issue by dmvk** [O2-Czech-Republic/proxima-platform#162]
`cz.o2.proxima.beam.core.BeamDataOperator#getBatchUpdates(org.apache.beam.sdk.Pipeline, long, long, boolean, cz.o2.proxima.repository.AttributeDescriptor<?>...)` does not filter out elements greater or equal than provided `end timestamp`.

`End timestamp` is currently only used to filter out input partitions.

**Comment by je-ik** [comment]
Will be fixed as part of #184
