### ISSUE TITLE
Outage of tests running on Stage env.

### ISSUE THREAD

**Issue by yshadow** [O2-Czech-Republic/proxima-platform#23]
We have encountered outage of tests running on stage env. Logs are enclosed below.

Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 1782419
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at cz.o2.proxima.storage.kafka.KafkaCommitLog$2.onPartitionsAssigned(KafkaCommitLog.java:417)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:265)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:367)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:316)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:297)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1078)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1043)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at cz.o2.proxima.storage.kafka.KafkaCommitLog.processConsumerWithObserver(KafkaCommitLog.java:563)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at cz.o2.proxima.storage.kafka.KafkaCommitLog.processConsumer(KafkaCommitLog.java:525)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at cz.o2.proxima.storage.kafka.KafkaCommitLog.lambda$observePartitionsBulk$7(KafkaCommitLog.java:432)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at java.lang.Thread.run(Thread.java:748)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: Caused by: java.lang.ArrayIndexOutOfBoundsException: 1782419
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at org.apache.hadoop.fs.FSOutputSummer.write(FSOutputSummer.java:76)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.write(FSDataOutputStream.java:50)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at java.io.DataOutputStream.writeInt(DataOutputStream.java:197)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at org.apache.hadoop.io.SequenceFile$Writer.sync(SequenceFile.java:1299)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at org.apache.hadoop.io.SequenceFile$BlockCompressWriter.sync(SequenceFile.java:1539)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at org.apache.hadoop.io.SequenceFile$BlockCompressWriter.close(SequenceFile.java:1569)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at cz.o2.proxima.storage.hdfs.HdfsDataAccessor.rollback(HdfsDataAccessor.java:125)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at cz.o2.proxima.server.IngestServer$3.onRestart(IngestServer.java:885)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011at cz.o2.proxima.storage.kafka.KafkaCommitLog$2.onPartitionsAssigned(KafkaCommitLog.java:397)
Nov  9 08:38:41 mujsignal-205 pexeso-ingest[1144]: #011... 10 more

**Comment by je-ik** [comment]
This might be related to the fact that HDFS was not available at that moment. Nevertheless, this should not cause outage. Need to investigate this further.

**Comment by je-ik** [comment]
Obsolete.
