### ISSUE TITLE
cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.consumer.internals.Fetcher produces enormous amount of logs when DEBUG level is set

### ISSUE THREAD

**Issue by yshadow** [O2-Czech-Republic/proxima-platform#64]
This class produces enormous amount of logs when DEBUG  level is set. Is it necessary?

**Comment by je-ik** [comment]
Yes, the logs are coming from kafka client. The solution is either to use info level globally, or to set info level on this particular class or package cz.o2.proxima. Important logs coming from this package are supposed to be at info level or higher.
