### ISSUE TITLE
Break down AttributeDescriptor not to contain writers and scheme serializers

### ISSUE THREAD

**Issue by je-ik** [O2-Czech-Republic/proxima-platform#66]
Redesign `Repository` so that it contains separate descriptors of entities, attributes, attribute families and views and has separate methods to retrieve all runtime needed accessors (writers, readers, view accessors, scheme serializers, ...).

**Comment by je-ik** [comment]
Another remark for this - currently attribute family contains specifications for both readers and writers that apply to it. That is fundamentally wrong, because the read settings might (and will) be dependent on the actual reader (type of processing involved). We need to break the whole specification to:
 - **descriptors** (entities, attributes, transforms, views)
 - **attribute families** - physical storage, not including any settings for neither write nor read
 - **accessors** - settings for write (single) and customizable settings for read using particular attribute family - this might also include settings about what strategy to choose when multiple options exist for a attribute family select choice (e.g. multiple commit logs, multiple families that can serve given access, etc.)

@JozoVilcek would you have any feedback or thoughts on this?

**Comment by JozoVilcek** [comment]
I have nothing to add. Breakdown of responsibilities sounds right to me.

**Comment by je-ik** [comment]
Done.
