### ISSUE TITLE
Add test coverage to build

### ISSUE THREAD

**Issue by je-ik** [O2-Czech-Republic/proxima-platform#97]
We need to improve overall test coverage by incorporating automatic test coverage report and failing build on low coverage conditions.

**Comment by LesTR** [comment]
@je-ik this can be closed. Fixed by https://github.com/datadrivencz/proxima-platform/pull/97 and https://github.com/datadrivencz/proxima-platform/pull/104

**Comment by je-ik** [comment]
Cool, thanks!
